### ISSUE TITLE
Summary 'No tests found'

### ISSUE THREAD

**Issue by dszakallas** [scottcorgan/tap-spec#47] opened 2016-08-03 10:06 UTC
```
>cat test
1..1
ok 1 Description
# tests 1
# pass 1
# fail 0
> cat test | node_modules/.bin/tap-spec
    ✔ Description


  ✖ No tests found
```

Why does `tap-spec` give this misleading summary?

**Comment by szdavid92** [comment] 2016-08-03 10:17
The output is from `mocha` run with the tap reporter.

**Comment by scottcorgan** [comment] 2016-08-03 13:41
Does it do the same thing when you using [tap](https://www.npmjs.com/package/tap) or [tape](https://www.npmjs.com/package/tape)?

Also, if you're using mocha, maybe try the spec reporter that comes with mocha. `tap-spec` is based off of that.

**Comment by szdavid92** [comment] 2016-08-03 14:55
No, `tape` works alright.
The problem is that the test cases (`describe` blocks) don't print a diagnostic messages with their name, like `tape` tests do, so the problem is that the assertions are just there unorganized. The problem with the spec reporter is that I want to run test in child processes and pipe them back to the parent and this creates a complete mess with that reporter.

**Comment by scottcorgan** [comment] 2016-08-03 15:10
Have you checked out [ava](https://github.com/avajs/ava)? Runs tests in parallel

**Comment by szdavid92** [comment] 2016-08-03 16:52
Currently mocha is the standard in my team, but for this project I eventually came to the decision to use it alongside with `tape` for these kind of tests, because of the TAP support. Test times is not yet of a concern in this project, if that's the major improvement in ava. Anyways, will check it out, thanks.

**Comment by scottcorgan** [comment] 2016-08-03 17:01
Nice.

I started a follow up to `tap-spec` called [`@tap-format/spec`](https://github.com/tap-format/spec). You can try that out if you'd like while this is looked into.

**Comment by lostcreation** [comment] 2016-09-07 14:54
I noticed this issue today, too, using Node v6.5.0, tape v4.6.0, and tape-spec v4.1.1.

I uploaded a minimal test case to my GitHub, the repo is [here](https://github.com/lostcreation/test-spec-issue.git).

**Comment by scottcorgan** [comment] 2016-09-07 15:02
@lostcreation, do you mind trying [`@tap-format/spec`](https://github.com/tap-format/spec) to see if you get the same error. It's the same kind of package, just better formatting. I've been meaning to add docs.

**Comment by lostcreation** [comment] 2016-09-07 15:10
Just tried it. `@tap-format/spec` works fine. I didn't see any problems with the test names that were tripping up `tap-spec`.

**Comment by scottcorgan** [comment] 2016-09-07 15:17
@lostcreation I'd recommend using that package over this one. Eventually this one will be replaced by `@tap-format/spec`

**Comment by lostcreation** [comment] 2016-09-07 15:21
Good to know. Thanks, Scott!

**Comment by MegaArman** [comment] 2017-01-19 04:06
Interestingly, I've found if my first test has three or more words (ex: 'mov 1 test') I get this error. That's the only time I get it from what I've found.

**Comment by drschwabe** [comment] 2017-08-24 09:33
Noticed this problem to, pinpointed it to having an integer in the name of test.  Ie:  `test("Explode 3 apples")` will cause this issue but `test("Explode three apples")` is AOK

**Comment by maxlutay** [comment] 2018-05-27 16:11
Probably fix #60

**Comment by scottcorgan** [comment] 2018-05-29 13:05
#60 has been merged. Can y'all confirm this is fixed now?

**Comment by scottcorgan** [comment] 2018-06-05 08:47
Going to close this now as this is probably fixed now.

**Closed by scottcorgan** 2018-06-05 08:47 UTC
